// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJSKIjMYdR9ZylLMlW3y3wXqf8xmBpxA',
    appId: '1:822905354803:web:809fb4f1508ad156edc146',
    messagingSenderId: '822905354803',
    projectId: 'asky-e73ad',
    authDomain: 'asky-e73ad.firebaseapp.com',
    storageBucket: 'asky-e73ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXWx3nHaEqaGyF3YLfIOHBB6Q47U37W-U',
    appId: '1:822905354803:android:fd385daf39eb4f12edc146',
    messagingSenderId: '822905354803',
    projectId: 'asky-e73ad',
    storageBucket: 'asky-e73ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQCT-GTVWhy-5v5ocU6OYcN54Hh4FjD8',
    appId: '1:822905354803:ios:3733a3a3d53afe17edc146',
    messagingSenderId: '822905354803',
    projectId: 'asky-e73ad',
    storageBucket: 'asky-e73ad.firebasestorage.app',
    iosBundleId: 'com.asky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQCT-GTVWhy-5v5ocU6OYcN54Hh4FjD8',
    appId: '1:822905354803:ios:2a28fca4341e6207edc146',
    messagingSenderId: '822905354803',
    projectId: 'asky-e73ad',
    storageBucket: 'asky-e73ad.firebasestorage.app',
    iosBundleId: 'com.example.asky',
  );
}
